build: Fix Boost 1.71 C++17 compatibility on macOS
Boost 1.71 uses std::unary_function which was removed in C++17.
Modern libc++ (Xcode 16+) enforces this removal by default.

Add -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION to restore
the deprecated types for Boost compatibility.

Error fixed:
  boost/container_hash/hash.hpp:130: error: no template named
  'unary_function' in namespace 'std'

TODO: Remove this workaround when upgrading Boost to 1.76+